service: document-gateway
frameworkVersion: '3'
plugins:
  - serverless-esbuild
  - serverless-offline
custom:
  esbuild:
    minify: true
    watch:
      # anymatch-compatible definition (https://github.com/es128/anymatch)
      pattern: ['./index.ts', 'src/**/*.ts'] # default .
      ignore: ['.serverless/**/*', '.build'] # default ['.build', 'dist', 'node_modules']

provider:
  name: aws
  runtime: nodejs16.x

functions:
  main:
    handler: src/index.handler
    events:
      - http:
          path: main
          method: get

